"""Initial

Revision ID: f470fddb5d50
Revises: 
Create Date: 2024-04-12 07:57:59.050416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f470fddb5d50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('students',
    sa.Column('student_guid', sa.UUID(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('student_guid')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_guid', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('visit', sa.Enum('VISITED', 'SKIPPED', 'SKIPPED_WITH_REASON', 'OTHER_GROUP', name='visitenum'), nullable=False),
    sa.ForeignKeyConstraint(['student_guid'], ['students.student_guid'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    op.create_table('banned_subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('subgroups',
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subgroup_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('subgroup_id')
    )
    op.create_table('students_subgroups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_guid', sa.UUID(), nullable=False),
    sa.Column('subgroup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_guid'], ['students.student_guid'], ),
    sa.ForeignKeyConstraint(['subgroup_id'], ['subgroups.subgroup_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_subgroups_id'), 'students_subgroups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_subgroups_id'), table_name='students_subgroups')
    op.drop_table('students_subgroups')
    op.drop_table('subgroups')
    op.drop_table('banned_subjects')
    op.drop_table('attendance')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('groups')
    # ### end Alembic commands ###
